### ISSUE TITLE
Cannot get any notification to show

### ISSUE THREAD

**Issue by andyipod1437** [ronny3050/phone-notification-mirror#1]
I cannot get any notification to show on my magic mirror. I see the box. But when my phone gets a notification not shows. Please help

**Comment by DjDOESIT** [comment]
Hello,
I have the same problem, I have added the KEY API but no notification on the screen.

**Comment by ronny3050** [comment]
Could you please try the latest push?

**Comment by andyipod1437** [comment]
It fix it over time. Had no idea what was wrong
