### ISSUE TITLE
Wrong example for config.js....

### ISSUE THREAD

**Issue by cowboysdude** [ronny3050/phone-notification-mirror#10]
You are using this  as an example ->

modules: [
	{
		    module: 'phone_notification',
            position: 'bottom_right',
            header: 'Phone Notifications',
            config:{
                accessToken: 'YOUR_ACCESS_TOKEN',
                numberOfNotifications: 5,
                displayNotificationIcon: true,
                displayMessage: true,
                displayCount: false,
                alert: false,
                fade: true,
                maxCharacters: 50
            },
	}
]

It's confusing new users... the module array already starts at the top.. people are trying to add your config example as written and it's not going to work ;)   

Please change example to this ->

	{
		    module: 'phone_notification',
            position: 'bottom_right',
            header: 'Phone Notifications',
            config:{
                accessToken: 'YOUR_ACCESS_TOKEN',
                numberOfNotifications: 5,
                displayNotificationIcon: true,
                displayMessage: true,
                displayCount: false,
                alert: false,
                fade: true,
                maxCharacters: 50
            }
	},

**Comment by ronny3050** [comment]
Thank you so much for the correction! 👍 :)
