### ISSUE TITLE
Service stopping after roughly 1 minute

### ISSUE THREAD

**Issue by lbengtson1** [ronny3050/phone-notification-mirror#17]
Everything is installed correctly and works as should, for about a minute.

In order to get the module to work again (for only 1 minute more), all I have to do is restart the mirror, but then back to nothing.  

I love the module, and would love to have pointed out what I am doing wrong.

Thanks!

**Comment by ronny3050** [comment]
That is really strange. I am really sorry you're facing this issue.
 Would you mind posting the logs?

**Comment by SashaCCCP** [comment]
Hello guys, i have the same problem with my MM , after every restart of my MM phone notifications work for about minute, #ronny3050 plsz help I really like ur module. Greeting Sasha

**Comment by chrisbutler** [comment]
@ronny3050 i'm seeing the same issue. which logs would you like to see?
