### ISSUE TITLE
Module not working

### ISSUE THREAD

**Issue by sharma-ji** [ronny3050/phone-notification-mirror#18]
I installed the module correctly and got the API as well but I can't see notifications on my magicmirror
 

![capture](https://user-images.githubusercontent.com/17575809/29536436-711196b4-86db-11e7-951e-b3c314b0b882.PNG)

**Comment by BRdev** [comment]
I've exactly the same problem. API access is present with the right Access Token key in my config file.

**Comment by chrisbutler** [comment]
i'm also having the same issue... @ronny3050 any thoughts? i'm willing to dig in and submit a PR
