### ISSUE TITLE
No phone notifications being displayed

### ISSUE THREAD

**Issue by jamesrequa** [ronny3050/phone-notification-mirror#2]
After following all the installation and config steps the module isn't displaying any of the phone notifications. Note I am using iOS and Raspberry Pi 3. 

Any suggestions for what the issue might be?

**Comment by fvi21** [comment]
The same problem here. Some idea?
Thanks in advance.

**Comment by ronny3050** [comment]
Unfortunately, it seems like iOS does not support push notifications.

**Comment by Army0104** [comment]
I do have this issue too. No notification is being displayed. Using android.

**Comment by huntersiniard** [comment]
I am not getting notifications either, but when i do the "send test notification" from the pushbullet app on my phone it works

**Comment by ronny3050** [comment]
Could you kindly post your log?

**Comment by ronny3050** [comment]
Please post your logs so I can see what is going on. I may have to close this issue otherwise.

**Comment by cosmopoliteaman** [comment]
It is not display the notification..

**Comment by cosmopoliteaman** [comment]
It's shows no new notifications
