### ISSUE TITLE
Error icons

### ISSUE THREAD

**Issue by triseaux** [ronny3050/phone-notification-mirror#4]
Hi,
When i have new notification, in serverside i have this error
`{ [Error: EACCES: permission denied, open '/home/pi/MagicMirror/modules/phone_notification/icons/Pushbullet.jpg']
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/pi/MagicMirror/modules/phone_notification/icons/Pushbullet.jpg' }
`
I check but i dont have any files in this foldier and you dont have also in your git.

**Comment by ronny3050** [comment]
Could try giving full access to your icons folder? `chmod 777 icons`. Afterwards, restart pi and please let me know if that fixed it.

Thanks!

**Comment by ronny3050** [comment]
@triseaux did it work?

**Comment by triseaux** [comment]
Hey, sorry i have lot of work and for the moment mi Miror is offline and i have to rebuild.
But i have look into the foldier and i dont see the IMG files, its normal ?

**Comment by ronny3050** [comment]
Could you please re-run the mirror and note whether any images are being saved after you run ``chmod 777 icons`` command?

**Comment by triseaux** [comment]
Hey, i have restart mi mirror, when i add 777 permissions on icon foldier, all is fonctional and no error message, ty for help.
