### ISSUE TITLE
Notifications not showing

### ISSUE THREAD

**Issue by Bluedino123** [ronny3050/phone-notification-mirror#6]
Whenever I do the test notification from pushbullet it works however any other types of notifications will not pop up.

**Comment by Bluedino123** [comment]
I figured out that my access token was typed in incorrectly and I'm getting notifications from emails and stuff but I'm not getting text notifications. Is there a way to fix that?

**Comment by ronny3050** [comment]
I don't think text notifications are allowed using Pushbullet. I would like to have them shown as well, but I could not find a way to do that. I apologize for any inconvenience caused.
