### ISSUE TITLE
phone-notification-mirror no notification

### ISSUE THREAD

**Issue by michael24h** [ronny3050/phone-notification-mirror#7]
first I have sing up at phushbullet.com
Also installed phushbullet app on iPhone
Then I have installed like the Readme file says.
But no notification will displayed. how i can fix the issue.

**Comment by dbankston2** [comment]
Same. It recognizes incoming calls and changes immediately, but after I take/miss/ignore the call it still says incoming instead of switching to the "missed call" notification. I know it's working because pushbullet pushes all of ti to my computer without issue.

**Comment by Germanfragger** [comment]
so yeah same here i wont get any notifications on my mirror is there a sort of debug/log to run/use?

**Comment by ronny3050** [comment]
After taking a look at this, @Germanfragger is correct in that some apps do not get push notifications from Pushbullet.  

I am closing this issue for now, please reopen if there's a common app that is not pushing notifications.
