### ISSUE TITLE
npm installation with reports about lack of repository and license

### ISSUE THREAD

**Issue by jznling** [ronny3050/phone-notification-mirror#9]
I have installed both your phone-notification-mirror and email-mirror. But both installation ends with No repository field and No license field. The module doesn't work after I load module in config.js

**Comment by ronny3050** [comment]
I am sorry to hear that. However, both the messages are warnings and have nothing to do with the mirror nor the modules. So there is some other reason the module is not working.

Would you mind posting your logs?
